
FROM alpine:latest
COPY $PWD/pwm-1.9.1.war /tmp/pwm.war
COPY $PWD/mysql-connector-java-8.0.17.jar /tmp/mysql-connector.jar
COPY $PWD/apache-tomcat-9.0.24.tar.gz /tmp/tomcat.tar.gz
RUN apk add openjdk8
RUN mkdir /usr/local/tomcat && \
	tar xf /tmp/tomcat.tar.gz && \
	mv apache-tomcat-9.0.24/* /usr/local/tomcat/ && \
	mv /tmp/pwm.war /usr/local/tomcat/webapps/ && \
	mv /tmp/mysql-connector.jar /usr/local/tomcat/lib/

CMD ["sh", "/usr/local/tomcat/bin/catalina.sh", "start"]
