name: Build

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
      - v1_9
    tags:
      - v*

  pull_request:

jobs:
  maven-build-publish:
    runs-on: ubuntu-latest
    steps:
      # checkout this repository
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build PWM
        run: mvn -B clean package -P skip-javadoc

      - name: Get project version
        run: |
          PWM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "::set-env name=PWM_VERSION::${PWM_VERSION}"

      - name: Store OneJar
        uses: actions/upload-artifact@v1
        with:
          name: onejar
          path: "onejar/target/pwm-onejar-${{ env.PWM_VERSION }}.jar"

      - name: Store WAR
        uses: actions/upload-artifact@v1
        with:
          name: war
          path: "webapp/target/pwm-${{ env.PWM_VERSION }}.war"

      - name: Publish to Github Packages
        run: mvn -B deploy
        env: 
          GITHUB_TOKEN: ${{ github.token  }}
      
