name: Build

on:
  push:
    branches:
      - master
      - v1_9
    tags:
      - v*

  pull_request:

jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
      # checkout this repository
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build PWM
      run: mvn clean package -P skip-javadoc,skip-docker

      - name: Collect build artifacts
        run: |
          PWM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          mkdir staging
          cp "webapp/target/pwm-${PWM_VERSION}.war" staging/pwm.war
          cp "onejar/target/pwm-onejar-${PWM_VERSION}.jar" staging/pwm-onejar.jar

      - name: Store artifacts
        uses: actions/upload-artifact@v1
        with:
          name: package
          path: staging
