name: Publish

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
      - v1_9
    tags:
      - v*

jobs:
  maven-build-publish:
    runs-on: ubuntu-latest
    steps:
      # checkout this repository
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - id: version
        name: Get application version
        run: |
          PWM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "PWM_VERSION=${PWM_VERSION}"
          echo "::set-output name=version::${PWM_VERSION}"

      - name: Build PWM
        run: mvn -B package

      - name: Upload OneJar
        uses: actions/upload-artifact@v1
        with:
          name: onejar
          path: "onejar/target/pwm-onejar-${{ steps.version.outputs.version }}.jar"

      - name: Upload WAR
        uses: actions/upload-artifact@v1
        with:
          name: war
          path: "webapp/target/pwm-${{ steps.version.outputs.version }}.war"

      - name: Upload Jib Docker image
        uses: actions/upload-artifact@v1
        with:
          name: docker-image
          path: "docker/target/pwm-docker-image-${{ steps.version.outputs.version }}.tar"

      - name: Publish to Github Packages
      run: mvn -B -Dmaven.wagon.http.pool=false -Dmaven.javadoc.skip=true deploy -s settings.xml -X
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
